#!/bin/bash
cd "$(dirname "$0")"/../../..
java --module-path /Users/work/Desktop/javafx-sdk-25.0.1/lib \
  --add-modules javafx.controls,javafx.fxml \
  -cp "bin:sqlite-jdbc.jar:slf4j-api.jar:slf4j-simple.jar" \
  com.yash.campuscashflow.Main
